[package]
name = "unciv"
version = "0.1.0"
edition = "2015"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
set-timestamps = []

[dependencies]
byteorder = "1.3"
png = "0.15"
